package com.marinerescue.model;

public enum Species {
    HARBOUR_SEAL, GRAY_SEAL, HARP_SEAL, BELUGA,
    WHITE_SIDED_DOLPHIN, PIOLET_WHALE, HARBOUR_PORPOISE, FIN_WHALE, SEI_WHALE, MINKIE_WHALE, HUMPBACK_WHALE, CORMORANT,
    LOON, SAND_PIPER, PUFFIN
}
